#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Sei Takahashi <seitaka_0716_poke@yahoo.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random

directions = ["右", "左", "右上", "左上", "真ん中","左下","右下"]


for direction in sys.stdin:
    direction = direction.strip()



    print(f"シュート方法は {direction} です。")

    keeper_choice = random.choice(directions)
    print(f"キーパーの動き: {keeper_choice}")

    if direction == keeper_choice:
        print("キーパーに止められた！")
    elif direction in ["右上", "左上", "右", "左"] and keeper_choice != direction:
        print("ゴール！素晴らしいシュート！")
    elif direction == "真ん中" and keeper_choice != "真ん中":
        print("パネンカを蹴った。ゴール！")
    else:
        print("枠外だ！惜しい！")

    print("--- PK戦終了 ---")
    break
