#!/usr/bin/python3
import sys



def tonum(s):
    try:
        return int(s)
    except:
        return float(s)




ant = 0
for line in sys.stdin:
    line = line.rstrip()
    ant += tonum(line)

ans = 0
for line in sys.stdin:
        ans += tonum(line)


print(ans)
