#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Sei Takahashi <seitaka_0716_poke@yahoo.com# SPDX-FileCopyrightText: 2024 Ryuichi Ueda# SPDX-FileCopyrightText: 2024 Ryuichi Ueda>
import sys


def tonum(s):
    try:
        return int(s)
    except:
        return float(s)


ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)
